### ISSUE TITLE
无法下载mod了

### ISSUE THREAD

**Issue by leirufentu** [WindyVerse/Panzer-War-Issues#12]
安卓决定版，无论是更换版本（从1.8.1~目前最新，再远的群文件失效了），重启手机，还是挂加速器，均无法下载模组😰
![Screenshot_2024-04-13-16-46-42-66_5e4c7a280f4a808083f40b62a3d32f34](https://github.com/WindyVerse/Panzer-War-Issues/assets/165913710/5f68c96c-3c39-4653-97a0-01967d08cd68)

**Comment by Doreamonsky** [comment]
挂VPN即可解决
