### ISSUE TITLE
关于BM21的后效问题与一个坦克工坊文字BUG

### ISSUE THREAD

**Issue by qwpuw** [WindyVerse/Panzer-War-Issues#4]
BM21虽是155，但后效与后效范围不符合（后效拉垮），另外希望未来添加更多火箭弹声
坦克工坊中的文字出现了BUG，原因未知，似乎是因为切屏导致的BUG
![}FL4%LX~5G}D9W0YF_WHIF_tmb](https://github.com/WindyVerse/Panzer-War-Issues/assets/165361804/2e81585c-e1e6-4fe4-9e19-4a71eee1cda6)

**Comment by qwpuw** [comment]
平台为Windows，Steam

**Comment by Doreamonsky** [comment]
会改善 bm21 的后效的
