### ISSUE TITLE
Crew voice mod not appearing

### ISSUE THREAD

**Issue by Nord-16** [WindyVerse/Panzer-War-Issues#7]
Windows 11
Steam

After installing crew voice mods from both built-in mod installer and steam workshop the crew voice does not show up in the crew voice setting.

**Comment by Doreamonsky** [comment]
which crew voice?

**Comment by Nord-16** [comment]
> which crew voice?

Every crew voice mod on steam workshop didn't work for me I tried reinstalling the mods and it still didn't work

**Comment by Doreamonsky** [comment]
saidly  old crew mods are not using fmod in the steam workshop. so they can not be displayed in the game.
